return {
  {
    "xiyaowong/nvim-transparent",
    lazy = false,
    priority = 1000,
    opts = {
      extra_groups = {
        "Normal",
        "NormalFloat",
        "NvimTreeNormal",
        "NonText",
        "SignColumn",
        "StatusLine",
        "StatusLineNC",
        "EndOfBuffer",
        "NormalNC",
        "TabLine",
        "TabLineFill",
        "TabLineSel",
        "Folded",
        "FoldColumn",
        "LineNr",
        "VertSplit",
        "FloatBorder",
        "TelescopeNormal",
        "TelescopeBorder",
        "WhichKeyFloat",
        "BufferLineTabClose",
        "BufferlineBufferSelected",
        "BufferLineFill",
        "BufferLineBackground",
        "BufferLineSeparator",
        "BufferLineIndicatorSelected",
      },
      exclude_groups = {
        "CursorLine",
        "CursorLineNr",
        "Search",
        "IncSearch",
        "Visual",
        "Pmenu",
      },
    },
    keys = {
      {
        "<leader>tt",
        "<cmd>lua require('transparent').toggle_transparent()<CR>",
        desc = "Toggle transparency",
      },
    },
  },
}
